### ISSUE TITLE
Build fails: template "report.html" not found

### ISSUE THREAD

**Issue by igneus** [martinellison/anglican_calendar#1]
(As the very first Rust program I've ever attempted to build) I cloned your repository and tried to bulid it, executing `scripts/build.sh`. The screenshot below shows the outcome. It looks like some essential files are missing in the repository, but given my level of Rust knowledge (pure zero), I'm not really sure about it.
![2020-06-21-162515_1366x768_scrot](https://user-images.githubusercontent.com/53101/85227298-e25acd00-b3dc-11ea-87e3-29cdaf78c988.png)

**Comment by martinellison** [comment]
That should be fixed now in the new release.
